import json
from fastapi import APIRouter, HTTPException, Query
from db.models import SavedAccount, CommunityMetadata, AccountRelationship, FollowEdge, Profile

router = APIRouter(prefix="/api/graph")

@router.get("/{alias}")
async def get_graph_data(
    alias: str, 
    mode: str = "macro", 
    limit: int = 1500, 
    seed_did: str = None, 
    community_id: int = None
):
    """
    Main entry point for graph data. Supports macro view, ego-networks, and circle packing.
    """
    owner = await SavedAccount.get_or_none(alias=alias)
    if not owner:
        raise HTTPException(status_code=404, detail="Account not found")

    if mode == "packing":
        # Circle Packing hierarchy: Communities -> Users
        communities = await CommunityMetadata.filter(owner=owner).all()
        children = []
        for comm in communities:
            members = await AccountRelationship.filter(owner=owner, community_id=comm.community_id).order_by("-flowrank_score").limit(100).prefetch_related("profile")
            children.append({
                "name": comm.name or f"Community {comm.community_id}",
                "id": comm.community_id,
                "children": [{
                    "did": m.did,
                    "handle": m.profile.handle,
                    "value": m.flowrank_score,
                    "display_name": m.profile.display_name,
                    "keywords": list((
                        json.loads(m.profile.top_keywords or "{}") if isinstance(m.profile.top_keywords, str) 
                        else (m.profile.top_keywords or {})
                    ).keys())[:3]
                } for m in members]
            })
        return {"name": "Root", "children": children}

    # Macro / Ego / Community Detail modes
    query = AccountRelationship.filter(owner=owner)
    if mode == "community" and community_id is not None:
        query = query.filter(community_id=community_id)
    
    nodes_data = await query.order_by("-flowrank_score").limit(limit).prefetch_related("profile")
    dids = [n.did for n in nodes_data]
    links = await FollowEdge.filter(follower_did__in=dids, followee_did__in=dids).values_list("follower_did", "followee_did")

    return {
        "nodes": [{
            "did": n.did, "handle": n.profile.handle, "rank": n.flowrank_score, 
            "comm": n.community_id, "cc": n.clustering_coefficient,
            "posts_count": n.profile.posts_count, "followers_count": n.profile.followers_count
        } for n in nodes_data],
        "links": [{"source": f, "target": t} for f, t in links],
        "metadata": {"node_count": len(nodes_data), "link_count": len(links)}
    }

@router.get("/{alias}/community/{community_id}")
async def get_community_detail(alias: str, community_id: int):
    """
    Returns detailed metadata for a specific community cluster.
    Data is generated by the graph analyzer in metrics.py.
    """
    owner = await SavedAccount.get_or_none(alias=alias)
    if not owner:
        raise HTTPException(status_code=404, detail="Account not found")

    community = await CommunityMetadata.get_or_none(owner=owner, community_id=community_id)
    if not community:
        # Return a skeleton response if analysis hasn't run yet
        return {
            "id": community_id,
            "name": f"Community #{community_id}",
            "description": "No metadata available for this community. Run graph analysis to generate summaries.",
            "top_keywords": {},
            "representative_members": []
        }

    return {
        "id": community.community_id,
        "name": community.name,
        "description": community.description,
        "top_keywords": community.top_keywords,
        "representative_members": community.representative_members
    }